/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

public class App {

	static final String FUNCTION_ENCRYPT_DOC 		= "EncryptDoc";
	static final String FUNCTION_DECRYPT_KEY_PART 	= "DecryptKeyPart";
	static final String FUNCTION_DECRYPT_DOC		= "DecryptDoc";

    public static void main(String[] args) {

		if(args.length == 0)
		{
			ErrorMsg.funcErrorMsg();
			System.exit(0);
		}

		try {
			Func func = new Func();

			String funcName = args[0];

			switch (funcName) {
				case FUNCTION_ENCRYPT_DOC:
					String encInfo = func.EncryptDocument(args);

					System.out.println(encInfo);
					break;
				case FUNCTION_DECRYPT_KEY_PART:
					String decryptKeyPart = func.DecryptKeyPart(args);
				
					System.out.println(decryptKeyPart);
					break;
				case FUNCTION_DECRYPT_DOC:
					String docStr = func.DecryptDoc(args);

					System.out.println(docStr);
					break;
				default:
					ErrorMsg.funcErrorMsg();
					System.exit(0);
					break;
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
    }
}
